apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swift-bridge-homologation
  annotations:
    argo.octopus.com/project: "swift-bridge"
    argo.octopus.com/environment: "homologation"
spec:
  project: default
  source:
     repoURL: https://github.com/OctopusSolutionsEngineering/ghu-swift-bridge.git
     targetRevision: HEAD
     path: Kubernetes/Manifests/homologation
  destination:
    server: https://kubernetes.default.svc
    namespace: homologation
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true